In [2]:
from utils.circs import append_basis_change_circuit
from qiskit import QuantumCircuit
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

In [22]:
import numpy as np

qc = QuantumCircuit(5, 5)
qc.h(0)
qc.h(1)
qc.cz(0, 1)
qc.h(0)
qc.h(1)
qc.h(2)
qc.h(3)
qc.cz(2, 3)
qc.h(2)
qc.h(3)
qc.measure(np.arange(4), np.arange(4))
qc.draw()

┌───┐   ┌───┐┌─┐         
q_0: ┤ H ├─■─┤ H ├┤M├─────────
     ├───┤ │ ├───┤└╥┘┌─┐      
q_1: ┤ H ├─■─┤ H ├─╫─┤M├──────
     ├───┤   ├───┤ ║ └╥┘┌─┐   
q_2: ┤ H ├─■─┤ H ├─╫──╫─┤M├───
     ├───┤ │ ├───┤ ║  ║ └╥┘┌─┐
q_3: ┤ H ├─■─┤ H ├─╫──╫──╫─┤M├
     └───┘   └───┘ ║  ║  ║ └╥┘
q_4: ──────────────╫──╫──╫──╫─
                   ║  ║  ║  ║ 
c: 5/══════════════╩══╩══╩══╩═
                   0  1  2  3

In [4]:
from cobos.tokens import ibm_token, group_instance
from qiskit_ibm_runtime.fake_provider import FakeSherbrooke

service = QiskitRuntimeService(channel="ibm_quantum", token=ibm_token, instance=group_instance)
backend = FakeSherbrooke()

In [23]:
pm = generate_preset_pass_manager(backend=backend, initial_layout=[0, 1, 2, 3, 4], optimization_level=2)
tqc = pm.run(qc)
tqc.draw(idle_wires=False)

global phase: π/2
         ┌─────────┐ ┌────┐┌─────────────┐┌────┐┌─────────┐┌──────┐»
q_0 -> 0 ┤ Rz(π/2) ├─┤ √X ├┤ Rz(-1.9731) ├┤ √X ├┤ Rz(π/2) ├┤1     ├»
         ├─────────┴┐├────┤├─────────────┤└────┘└─────────┘│  Ecr │»
q_1 -> 1 ┤ Rz(-π/2) ├┤ √X ├┤ Rz(-2.0406) ├─────────────────┤0     ├»
         ├─────────┬┘├────┤├─────────────┤┌────┐┌─────────┐├──────┤»
q_2 -> 2 ┤ Rz(π/2) ├─┤ √X ├┤ Rz(-1.9731) ├┤ √X ├┤ Rz(π/2) ├┤1     ├»
         ├─────────┴┐├────┤├─────────────┤└────┘└─────────┘│  Ecr │»
q_3 -> 3 ┤ Rz(-π/2) ├┤ √X ├┤ Rz(-2.0406) ├─────────────────┤0     ├»
         └──────────┘└────┘└─────────────┘                 └──────┘»
    c: 5/══════════════════════════════════════════════════════════»
                                                                   »
«           ┌─────────┐   ┌────┐┌─────────────┐┌────┐┌─────────┐           ┌─┐»
«q_0 -> 0 ──┤ Rz(π/2) ├───┤ √X ├┤ Rz(-2.7393) ├┤ √X ├┤ Rz(π/2) ├───────────┤M├»
«         ┌─┴─────────┴──┐├────┤└─┬─────────┬─┘└────┘└───┬─┬───┘           └╥┘»
«q_1 -> 1 ┤ Rz(-0.46978) ├┤ √X ├──┤ Rz(π/2) ├────────────┤M├────────────────╫─»
«         └─┬─────────┬──┘├────┤┌─┴─────────┴─┐┌────┐    └╥┘    ┌─────────┐ ║ »
«q_2 -> 2 ──┤ Rz(π/2) ├───┤ √X ├┤ Rz(-2.7393) ├┤ √X ├─────╫─────┤ Rz(π/2) ├─╫─»
«         ┌─┴─────────┴──┐├────┤└─┬─────────┬─┘└┬─┬─┘     ║     └─────────┘ ║ »
«q_3 -> 3 ┤ Rz(-0.46978) ├┤ √X ├──┤ Rz(π/2) ├───┤M├───────╫─────────────────╫─»
«         └──────────────┘└────┘  └─────────┘   └╥┘       ║                 ║ »
«    c: 5/═══════════════════════════════════════╩════════╩═════════════════╩═»
«                                                3        1                 0 »
«            
«q_0 -> 0 ───
«            
«q_1 -> 1 ───
«         ┌─┐
«q_2 -> 2 ┤M├
«         └╥┘
«q_3 -> 3 ─╫─
«          ║ 
«    c: 5/═╩═
«          2

In [24]:
tqc.depth(lambda x: len(x.qubits)>1)

1

In [6]:
tqc.data

[CircuitInstruction(operation=Instruction(name='rz', num_qubits=1, num_clbits=0, params=[-1.5707963267948966]), qubits=(Qubit(QuantumRegister(127, 'q'), 0),), clbits=()), CircuitInstruction(operation=Instruction(name='sx', num_qubits=1, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(127, 'q'), 0),), clbits=()), CircuitInstruction(operation=Instruction(name='rz', num_qubits=1, num_clbits=0, params=[1.5707963267948966]), qubits=(Qubit(QuantumRegister(127, 'q'), 0),), clbits=()), CircuitInstruction(operation=Instruction(name='x', num_qubits=1, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(127, 'q'), 1),), clbits=()), CircuitInstruction(operation=Instruction(name='ecr', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(127, 'q'), 1), Qubit(QuantumRegister(127, 'q'), 0)), clbits=()), CircuitInstruction(operation=Instruction(name='rz', num_qubits=1, num_clbits=0, params=[1.5707963267948966]), qubits=(Qubit(QuantumRegister(127, 'q'), 0),), clbits=()), Ci

In [16]:
from utils.hexec import execute_estimator_batch
from z2chain.operators import pauli_zs_mean

observable_generating_funcs = pauli_zs_mean

jobs = execute_estimator_batch(backend, {"default_precision": 1e-2}, tqc, observable_generating_funcs)
jobs[0].result()[0].data.evs

array([0.96848])

In [18]:
# from utils.circs import append_basis_change_circuit

# bctqc = append_basis_change_circuit(tqc, "X", backend)
# bctqc.draw(idle_wires=False)

In [19]:
import numpy as np

string = "1010"
string_arr = np.array([int(c) for c in string])
string_rep_arr = np.repeat(np.array([string_arr]), 5, axis=0)
string_rep_arr

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [20]:
from qiskit.quantum_info import Pauli, PauliList
from utils.postselection import is_valid_state_string

pops = PauliList([Pauli("ZZIII"), Pauli("IZZZI"), Pauli("IIIZZ")])
string = "11011"

is_valid_state_string(string, pops)

True

In [21]:
set(pops)

{Pauli('IIIZZ'), Pauli('IZZZI'), Pauli('ZZIII')}

In [8]:
from utils.postselection import measure_diagonal_observables

observables = PauliList([Pauli("ZIII"), Pauli("IIIZ"), Pauli("ZIIZ")])
samples_dict = {"1000": 95, "0000": 5}

measure_diagonal_observables(samples_dict, observables)

array([ 1. , -0.9, -0.9])